apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-hostpath-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  hostPath:
    Path: /mnt/mydata
    tyoe: DirectoryorCreate